# docker-compose.yml
version: '3'
services:
  server:
    build:
      context: ./server/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3001
    ports:
      - '3001:3001'
    command: npm run dev
    volumes:
      - ./server/:/server/
      - /server/node_modules
  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
